project_id = "nbvvdaprcecaqvvkqcto"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54326
site_url = "http://127.0.0.1:54321"
additional_redirect_urls = ["https://127.0.0.1:54321"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
email_enable_signup = true
sms_enable_signup = true
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
max_frequency = "1s"

[auth.sms]
enable_signup = true
enable_confirmations = false
max_frequency = "5s"

[functions.lead-webhook]
verify_jwt = false

[functions.einforma-enrich-company]
verify_jwt = true

[functions.einforma-test-connection]
verify_jwt = true

[functions.scheduled-reports]
verify_jwt = true

[functions.commission-notifications]
verify_jwt = true

[functions.generate_rod]
verify_jwt = true

[functions.send_campaign]
verify_jwt = true

[edge-runtime]
enabled = true
port = 54327
inspector_port = 54328

[analytics]
enabled = false
port = 54329
vector_port = 54330