
export const sampleOperations = [
  {
    company_name: "TechFlow Solutions",
    project_name: "Proyecto Aurora",
    sector: "Tecnología",
    operation_type: "sale",
    amount: 15000000,
    revenue: 15000000,
    ebitda: 3000000,
    annual_growth_rate: 25.0,
    currency: "EUR",
    date: "2024-12-15",
    status: "available",
    description: "Empresa líder en desarrollo de software empresarial con presencia en 5 países europeos. Especializada en soluciones CRM y ERP para medianas empresas.",
    location: "Madrid, España",
    contact_email: "info@techflow.com",
    contact_phone: "+34 91 123 4567",
    cif: "A12345678"
  },
  {
    company_name: "Green Energy Partners",
    project_name: "Proyecto Solaris",
    sector: "Energías Renovables",
    operation_type: "partial_sale",
    amount: 45000000,
    revenue: 45000000,
    ebitda: 12000000,
    annual_growth_rate: 18.5,
    currency: "EUR",
    date: "2024-11-20",
    status: "available",
    description: "Desarrollador y operador de parques solares con una cartera de 250 MW en operación y 100 MW en desarrollo.",
    location: "Valencia, España",
    contact_email: "investors@greenenergypartners.com",
    contact_phone: "+34 96 789 0123",
    cif: "B23456789"
  },
  {
    company_name: "HealthTech Innovations",
    project_name: "Proyecto Vitalis",
    sector: "Salud y Biotecnología",
    operation_type: "merger",
    amount: 8000000,
    revenue: 8000000,
    ebitda: 1200000,
    annual_growth_rate: 35.0,
    currency: "EUR",
    date: "2024-10-30",
    status: "available",
    description: "Startup pionera en telemedicina y dispositivos de monitoreo remoto de pacientes. Tecnología patentada con aprobación CE.",
    location: "Barcelona, España",
    contact_email: "contact@healthtech.es",
    contact_phone: "+34 93 456 7890",
    cif: "C34567890"
  },
  {
    company_name: "Industrial Logistics Corp",
    project_name: "Proyecto Nexus",
    sector: "Logística y Transporte",
    operation_type: "sale",
    amount: 22000000,
    revenue: 22000000,
    ebitda: 4500000,
    annual_growth_rate: 12.0,
    currency: "EUR",
    date: "2024-09-15",
    status: "available",
    description: "Red de centros logísticos estratégicamente ubicados con servicios de almacenamiento y distribución para e-commerce.",
    location: "Sevilla, España",
    contact_email: "info@industriallogistics.es",
    contact_phone: "+34 95 234 5678",
    cif: "D45678901"
  },
  {
    company_name: "FoodChain Innovations",
    project_name: "Proyecto Gourmet",
    sector: "Alimentación",
    operation_type: "buy_mandate",
    amount: 12000000,
    revenue: 12000000,
    ebitda: 2800000,
    annual_growth_rate: 20.0,
    currency: "EUR",
    date: "2024-08-25",
    status: "available",
    description: "Cadena de restaurantes gourmet con concepto innovador de cocina fusión. 15 ubicaciones premium en España.",
    location: "Bilbao, España",
    contact_email: "expansion@foodchain.es",
    contact_phone: "+34 94 567 8901",
    cif: "E56789012"
  }
];
