
import { Operation } from "@/types/Operation";

export const sampleOperationsData: Omit<Operation, "id" | "created_at" | "updated_at" | "created_by">[] = [
  {
    company_name: "Innovate Solutions SL",
    cif: "B87654321",
    sector: "Tecnología",
    operation_type: "sale",
    amount: 12000000,
    currency: "EUR",
    date: "2023-11-20",
    buyer: "Global Software Corp",
    seller: "Inversores Privados",
    status: "available",
    description: "Adquisición de empresa de software B2B especializada en automatización",
    location: "Barcelona",
    contact_email: "info@innovate.es",
    contact_phone: "+34 930 123 456",
    revenue: 8000000,
    ebitda: 1500000,
    annual_growth_rate: 30.0
  },
  {
    company_name: "Saludable Foods SA",
    cif: "A12345679",
    sector: "Alimentación",
    operation_type: "sale",
    amount: 7500000,
    currency: "EUR",
    date: "2024-03-10",
    buyer: "NutriVida Group",
    seller: "Familia fundadora",
    status: "available",
    description: "Venta de productor de alimentos orgánicos con certificación europea",
    location: "Valencia",
    contact_email: "contacto@saludablefoods.es",
    contact_phone: "+34 960 987 654",
    revenue: 10000000,
    ebitda: 1200000,
    annual_growth_rate: 15.5
  },
  {
    company_name: "EcoEnergía Renovables",
    cif: "B98765432",
    sector: "Energía",
    operation_type: "partial_sale",
    amount: 25000000,
    currency: "EUR",
    date: "2023-09-05",
    buyer: "Green Ventures Capital",
    seller: "EcoEnergía Renovables",
    status: "available",
    description: "Ronda de financiación para expansión en energía solar",
    location: "Sevilla",
    contact_email: "invest@ecoenergia.com",
    contact_phone: "+34 950 112 233",
    revenue: 15000000,
    ebitda: 3000000,
    annual_growth_rate: 45.0
  },
  {
    company_name: "Moda Global Retail",
    cif: "A23456789",
    sector: "Retail",
    operation_type: "merger",
    amount: 85000000,
    currency: "EUR",
    date: "2024-05-22",
    buyer: "Urban Style Co",
    seller: "Moda Global Retail",
    status: "pending_review",
    description: "Fusión para crear líder en moda joven con presencia internacional",
    location: "Madrid",
    contact_email: "press@modaglobal.com",
    contact_phone: "+34 910 334 455",
    revenue: 50000000,
    ebitda: 7500000,
    annual_growth_rate: 12.0
  },
  {
    company_name: "Logística Express 24h",
    cif: "B34567890",
    sector: "Logística",
    operation_type: "sale",
    amount: 3000000,
    currency: "USD",
    date: "2023-12-18",
    buyer: "Rapid Delivery Inc",
    seller: "Fundadores",
    status: "available",
    description: "Compra de startup de última milla con tecnología propia",
    location: "Zaragoza",
    contact_email: "admin@logisticaexpress.es",
    contact_phone: "+34 976 556 677",
    revenue: 4000000,
    ebitda: 400000,
    annual_growth_rate: 35.2
  }
];
